name: GPT Translate per Commit

on:
  push:
    branches:
      - main
jobs:
  gpt_translate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository with two latest commits
        uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: get changed files name
        id: changed_files
        run: |
          echo "files=$(git diff --name-only ${{ github.event.head }} ${{ github.event.head }} | grep '\.en\.md$' | tr '\n' ' ')" >> $GITHUB_OUTPUT

      - name: Run GPT Translate
        uses: drmingdrmer/gpt-translate@master
        with:
          apikey: ${{ secrets.OPENAI_API_KEY }}
          inputFiles: ${{ steps.changed_files.outputs.files }}
          outputFiles: '**/*.cn.md'
          languages: 'Chinese'
