name: GPT Translate per Commit

on:
  push:
    branches:
      - main
jobs:
  gpt_translate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository with two latest commits
        uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: get changed files name
        id: changed_files
          # echo "files=$(git diff --name-only "${{ github.event.before }}" "${{ github.event.head }}" | grep '\.en\.md$' | tr '\n' ' ')" >> $GITHUB_OUTPUT
        run: |
          echo "files=$(git diff --name-only HEAD^ HEAD | grep '\.en\.md$' | tr '\n' ' ')" >> $GITHUB_OUTPUT

      - name: Run GPT Translate
        uses: drmingdrmer/gpt-translate@master
        env:
          GITHUB_USERNAME: ${{ github.repository_owner }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          apikey: ${{ secrets.OPENAI_API_KEY_JUNJUN }}
          inputFiles: ${{ steps.changed_files.outputs.files }}
          outputFiles: '**/*.cn.md'
          languages: 'Chinese'
